spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swagger
    username: test
    password: root
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  batch:
    jdbc:
      initialize-schema: always
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /user-swagger.html
    operationsSorter: method